export const UI_START_ACTION = '@ui/START_ACTION';
export const UI_STOP_ACTION = '@ui/STOP_ACTION';

export const UI_REFRESH_ACTION_START = '@ui/REFRESH_ACTION_START';
export const UI_REFRESH_ACTION_STOP = '@ui/REFRESH_ACTION_STOP';
