// <auto-generated />
using EstoqueACPO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueACPO.Migrations
{
    [DbContext(typeof(EstoqueACPOContext))]
    [Migration("20201003190222_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("EstoqueACPO.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tenis Adidas",
                            Unidades = 5,
                            Valor = 79.9m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Bicicleta Monark",
                            Unidades = 2,
                            Valor = 200m
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Skol 350ml",
                            Unidades = 5,
                            Valor = 2.75m
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Ventilador ARNO",
                            Unidades = 85,
                            Valor = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
