export const GET_PRODUTOS_REQUEST = '@produto/GET_PRODUTOS_REQUEST';
export const GET_PRODUTOS_SUCCESS = '@produto/GET_PRODUTOS_SUCCESS';

export const CREATE_PRODUTO_REQUEST = '@produto/CREATE_PRODUTO_REQUEST';
export const CREATE_PRODUTO_SUCCESS = '@produto/CREATE_PRODUTO_SUCCESS';

export const UPDATE_PRODUTO_REQUEST = '@produto/UPDATE_PRODUTO_REQUEST';
export const UPDATE_PRODUTO_SUCCESS = '@produto/UPDATE_PRODUTO_SUCCESS';

export const DELETE_PRODUTO_REQUEST = '@produto/DELETE_PRODUTO_REQUEST';
export const DELETE_PRODUTO_SUCCESS = '@produto/DELETE_PRODUTO_SUCCESS';
